#!/bin/sh

ENABLED=yes
PROCS=mongoose
ARGS="/opt/etc/mongoose/mongoose.conf"
PREARGS="nohup"
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
