#!/opt/bin/bash

. /opt/var/lib/dlengine/utils
NAME="Download Engine"

start() {
  echo -n "Starting $NAME... "
  if ! daemonrunning
  then
    $DAEMON &
    echo "done."
  else
    echo "already running."
  fi
}

stop() {
  echo -n "Shutting down $NAME... "
  if daemonrunning
  then
    if [ -e $TASKPID ]
    then
      kill "`cat $TASKPID`" 2>/dev/null
      rm $TASKPID 2>/dev/null
    fi
    kill "`cat $MAINPID`" 2>/dev/null
    rm $MAINPID 2>/dev/null
    echo "done."
  else
    echo "not started."
  fi
}

reload() {
  echo -n "Reloading $NAME... "
  if [ -e $TASKPID ] && [ -n "`pidof $TOOL | grep -w -f $TASKPID`" ]
  then
    kill "`cat $TASKPID`" 2>/dev/null
    echo "done."
  else
    echo "nothing to do."
  fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    reload)
        reload
        ;;
    *)
        echo "Usage: $0 (start|stop|reload|restart)"
        exit 1
        ;;
esac
exit 0
