#!/bin/sh 

ENABLED=yes 
PROCS=dnscrypt-proxy 
ARGS="--local-port=65053 --user=nobody --daemonize" 
PREARGS="" 
DESC=$PROCS 
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 

. /opt/etc/init.d/rc.func 
