#!/bin/sh

start() {
echo "Starting httpd:"
/usr/sbin/busybox_httpd -c /opt/etc/httpd.conf -p 8080 -h /opt/share/www
}

stop() {
echo "Stopping httpd:"
killall busybox_httpd
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    *)
        echo "Usage: $0 (start|stop|restart)"
        exit 1
        ;;
esac
exit 0
