#!/bin/sh
# Notificator for *nix desktops
# If you whould like to see notfication messages place this script to crontab
# If for example you whould like to start this script every 50 minutes copy this script to
# /opt/sbin
# sudo cp fidomail /opt/sbin
# and add to crontab this string:
# */50 * * * * /opt/sbin/fidomail >/dev/null 2>&1  
# Script created by Vladimir Smagin - 2:5020/8080.21
#

rm -rf /opt/tmp/recv.tmp
/opt/sbin/recv 2> /opt/tmp/recv.tmp
bla=`cat /opt/tmp/recv.tmp |grep 'receiving'`
if [ -z "$bla" ]
then
    sleep 1
else
    echo "You've got new FIDO-messages! Start Golded for reading"
fi

rm -rf /opt/tmp/send.tmp
/opt/sbin/send 2> /opt/tmp/send.tmp
bla2=`cat /opt/tmp/send.tmp | grep 'sending'`
if [ -z "$bla2" ]
then
    sleep 1
else
    echo "You've sent your FIDO-messages! Your messages have been sent"
fi

rm -rf /opt/tmp/recv.tmp
rm -rf /opt/tmp/send.tmp
